name: fb_todo_app
description: A new Flutter project.

publish_to: 'none'


version: 1.0.0+1

environment:
  sdk: ">=2.17.0-138.0.dev <3.0.0"


dependencies:
  flutter:
    sdk: flutter


  cupertino_icons: ^1.0.2
  flutter_zoom_drawer:
  top_snackbar_flutter:
  firebase_auth: ^1.1.1
  firebase_core:
  firebase_storage:
  cloud_firestore:
  flutter_bloc:
  easy_localization:
  page_transition:
  progress_indicators:

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^1.0.0


flutter:

  uses-material-design: true


  assets:
    - assets/images/


  fonts:
    - family: arabic_font
      fonts:
        - asset: assets/fonts/custom_font.ttf
    - family: en_font
      fonts:
        - asset: assets/fonts/en_font.ttf
